//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning.Add2NumASMXService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://iqansweb.com/", ConfigurationName="Add2NumASMXService.Add2NumSoap")]
    public interface Add2NumSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iqansweb.com/Add", ReplyAction="*")]
        int Add(int iNum1, int iNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iqansweb.com/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int iNum1, int iNum2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Add2NumSoapChannel : Learning.Add2NumASMXService.Add2NumSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Add2NumSoapClient : System.ServiceModel.ClientBase<Learning.Add2NumASMXService.Add2NumSoap>, Learning.Add2NumASMXService.Add2NumSoap {
        
        public Add2NumSoapClient() {
        }
        
        public Add2NumSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Add2NumSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Add2NumSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Add2NumSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int iNum1, int iNum2) {
            return base.Channel.Add(iNum1, iNum2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int iNum1, int iNum2) {
            return base.Channel.AddAsync(iNum1, iNum2);
        }
    }
}
